ALTER TABLE "Material" ADD COLUMN "contentOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Quiz" ADD COLUMN "contentOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Assignment" ADD COLUMN "contentOrder" INTEGER NOT NULL DEFAULT 0;
