import { Router } from "express";
import multer from "multer";
import * as XLSX from "xlsx";
import path from "path";
import fs from "fs";
import { prisma } from "../lib/prisma.js";
import { requireAuth, requireRole } from "../middleware/auth.js";
import { CreateQuizSchema, SubmitQuizSchema } from "@repo/shared";

const r = Router();
const uploadDir = process.env.UPLOAD_DIR || "./uploads";
if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });
const imageUpload = multer({ storage: multer.diskStorage({ destination: (_req, _file, cb) => cb(null, uploadDir), filename: (_req, file, cb) => cb(null, `${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g, "_")}`) }), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: (_req, file, cb) => cb(null, /^image\/(jpeg|png|gif|webp)$/.test(file.mimetype)) });
const uploadRoot = path.resolve(uploadDir);
const localImagePath = (url?: string | null) => {
  if (!url?.startsWith("/uploads/")) return null;
  const filePath = path.resolve(uploadRoot, url.slice("/uploads/".length));
  return filePath.startsWith(`${uploadRoot}${path.sep}`) ? filePath : null;
};
const removeImageIfUnused = async (url?: string | null) => {
  const filePath = localImagePath(url);
  if (!filePath) return;
  const stillUsed = await prisma.question.count({ where: { imageUrl: url } });
  if (!stillUsed && fs.existsSync(filePath)) await fs.promises.unlink(filePath);
};
const excelUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });

const questionOut = (q: any, hide: boolean) => { const item = { ...q, options: typeof q.options === "string" ? JSON.parse(q.options) : q.options }; if (hide) delete item.correctIndex; return item; };
const quizOut = (q: any, hide = false) => ({ ...q, questions: q.questions?.map((item: any) => questionOut(item, hide)) });
r.use("/:id/submit", requireAuth as any, async (req: any, res, next) => { const quiz = await prisma.quiz.findUnique({ where: { id: req.params.id }, select: { deadline: true, archived: true } }); if (!quiz || quiz.archived) return res.status(404).json({ message: "Quiz tidak tersedia." }); if (quiz.deadline && quiz.deadline < new Date()) return res.status(403).json({ message: "Deadline quiz telah lewat." }); next(); });

r.get("/template", requireAuth as any, requireRole("ADMIN", "DOSEN") as any, (_req, res) => {
  const sheet = XLSX.utils.aoa_to_sheet([["title", "kind", "module", "passingScore", "timeLimit", "attemptLimit", "showAnswers", "question", "options", "correctIndex", "points", "imageUrl"], ["Quiz contoh", "QUIZ", "Modul 1", 60, "", -1, false, "Ibukota Indonesia?", "Jakarta||Bandung||Surabaya", 0, 10, ""]]);
  const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, "Questions");
  res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"); res.setHeader("Content-Disposition", "attachment; filename=template-soal.xlsx"); res.send(XLSX.write(book, { type: "buffer", bookType: "xlsx" }));
});

r.post("/upload-image", requireAuth as any, requireRole("ADMIN", "DOSEN") as any, imageUpload.single("file"), (req: any, res) => { if (!req.file) return res.status(400).json({ message: "File gambar wajib JPG, PNG, GIF, atau WEBP dan maksimal 5MB." }); res.status(201).json({ imageUrl: `/uploads/${req.file.filename}` }); });

r.get("/", requireAuth as any, async (req: any, res) => { const where: any = {}; if (req.query.courseId) where.courseId = req.query.courseId; if (req.query.moduleId) where.moduleId = req.query.moduleId; const qs = await prisma.quiz.findMany({ where, include: { questions: { orderBy: { order: "asc" } }, _count: { select: { questions: true } } }, orderBy: [{ order: "asc" }, { createdAt: "asc" }] }); res.json(qs.map((q: any) => quizOut(q, req.user.role === "MAHASISWA"))); });

r.get("/:id", requireAuth as any, async (req: any, res) => { const q = await prisma.quiz.findUnique({ where: { id: req.params.id }, include: { questions: { orderBy: { order: "asc" } }, module: true, course: true } }); if (!q || (q.archived && req.user.role === "MAHASISWA")) return res.status(404).json({ message: "Not found" }); res.json(quizOut(q, req.user.role === "MAHASISWA")); });

r.post("/", requireAuth as any, requireRole("ADMIN", "DOSEN") as any, async (req, res) => { const parsed = CreateQuizSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json(parsed.error); const { title, kind, courseId, moduleId, passingScore, timeLimit, attemptLimit, showAnswers, questions } = parsed.data; const quiz = await prisma.quiz.create({ data: { order: moduleId ? await prisma.quiz.count({ where: { moduleId } }) + 1 : 0, title, kind, courseId: courseId || null, moduleId: moduleId || null, passingScore, timeLimit: timeLimit ?? null, attemptLimit, showAnswers, deadline: req.body.deadline ? new Date(req.body.deadline) : null, archived: req.body.archived === true } }); await prisma.question.createMany({ data: questions.map((q, i) => ({ quizId: quiz.id, order: q.order ?? i + 1, text: q.text, options: JSON.stringify(q.options), correctIndex: q.correctIndex, points: q.points, imageUrl: q.imageUrl || null })) }); const full = await prisma.quiz.findUnique({ where: { id: quiz.id }, include: { questions: true } }); res.status(201).json(quizOut(full)); });

r.post("/import", requireAuth as any, requireRole("ADMIN", "DOSEN") as any, excelUpload.single("file"), async (req: any, res) => {
  if (!req.file) return res.status(400).json({ message: "File Excel wajib dipilih." }); const courseId = String(req.body.courseId || ""); if (!courseId) return res.status(400).json({ message: "courseId wajib diisi." });
  try {
    const workbook = XLSX.read(req.file.buffer, { type: "buffer" }); const sheet = workbook.Sheets.Questions || workbook.Sheets[workbook.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json(sheet, { defval: "" }) as any[]; if (!rows.length) return res.status(400).json({ message: "Sheet Excel tidak berisi soal." });
    const modules = await prisma.module.findMany({ where: { courseId } }); const byKey = new Map(modules.flatMap((m) => [[m.id, m], [m.title.trim().toLowerCase(), m]])); const groups = new Map<string, any>(); const errors: string[] = [];
    rows.forEach((row, i) => { const line = i + 2; const title = String(row.title || "").trim(); const mod = byKey.get(String(row.module || "").trim().toLowerCase()); const options = String(row.options || "").split("||").map((x) => x.trim()).filter(Boolean); const correctIndex = Number(row.correctIndex); const attemptLimit = row.attemptLimit === "" ? -1 : Number(row.attemptLimit); const before = errors.length; if (!title) errors.push(`Baris ${line}: title wajib diisi.`); if (!mod) errors.push(`Baris ${line}: module tidak ditemukan.`); if (!String(row.question || "").trim()) errors.push(`Baris ${line}: question wajib diisi.`); if (options.length < 2) errors.push(`Baris ${line}: minimal 2 opsi.`); if (!Number.isInteger(correctIndex) || correctIndex < 0 || correctIndex >= options.length) errors.push(`Baris ${line}: correctIndex tidak valid.`); if (!Number.isInteger(attemptLimit) || attemptLimit < -1) errors.push(`Baris ${line}: attemptLimit harus -1, 0, atau bilangan positif.`); if (errors.length > before) return; const key = `${title}\u0000${mod!.id}`; if (!groups.has(key)) groups.set(key, { title, moduleId: mod!.id, kind: row.kind || "QUIZ", passingScore: Number(row.passingScore || 60), timeLimit: row.timeLimit === "" ? null : Number(row.timeLimit), attemptLimit, showAnswers: row.showAnswers === true || String(row.showAnswers).toLowerCase() === "true", questions: [] }); groups.get(key).questions.push({ text: String(row.question).trim(), options, correctIndex, points: Number(row.points || 10), imageUrl: String(row.imageUrl || "").trim() || null }); });
    if (errors.length) return res.status(400).json({ message: "Import gagal. Perbaiki baris berikut.", errors });
    const result = await prisma.$transaction(async (tx) => { let questionCount = 0; for (const data of groups.values()) { const q = await tx.quiz.create({ data: { title: data.title, kind: data.kind, courseId, moduleId: data.moduleId, passingScore: data.passingScore, timeLimit: data.timeLimit, attemptLimit: data.attemptLimit, showAnswers: data.showAnswers } }); await tx.question.createMany({ data: data.questions.map((item: any, i: number) => ({ quizId: q.id, order: i + 1, text: item.text, options: JSON.stringify(item.options), correctIndex: item.correctIndex, points: item.points, imageUrl: item.imageUrl })) }); questionCount += data.questions.length; } return { quizCount: groups.size, questionCount }; }); res.status(201).json(result);
  } catch (error: any) { res.status(400).json({ message: `Import gagal: ${error.message || "format file tidak valid"}` }); }
});

r.put("/:id", requireAuth as any, requireRole("ADMIN", "DOSEN") as any, async (req, res) => { const { questions, ...quizData } = req.body; const oldImages = Array.isArray(questions) ? (await prisma.question.findMany({ where: { quizId: req.params.id }, select: { imageUrl: true } })).map((item) => item.imageUrl) : []; const q = await prisma.$transaction(async (tx) => { await tx.quiz.update({ where: { id: req.params.id }, data: quizData }); if (Array.isArray(questions)) { await tx.question.deleteMany({ where: { quizId: req.params.id } }); await tx.question.createMany({ data: questions.map((item: any, i: number) => ({ quizId: req.params.id, order: item.order ?? i + 1, text: item.text, options: JSON.stringify(item.options), correctIndex: item.correctIndex, points: item.points ?? 10, imageUrl: item.imageUrl || null })) }); } return tx.quiz.findUnique({ where: { id: req.params.id }, include: { questions: { orderBy: { order: "asc" } } } }); }); await Promise.all(oldImages.filter((url: string | null) => url).map((url: string | null) => removeImageIfUnused(url))); if (!q) return res.status(404).json({ message: "Not found" }); res.json(quizOut(q)); });
r.patch("/:id/reorder", requireAuth as any, requireRole("ADMIN", "DOSEN") as any, async (req: any, res) => { const current = await prisma.quiz.findUnique({ where: { id: req.params.id } }); if (!current?.moduleId) return res.status(400).json({ message: "Quiz harus memiliki modul." }); const items = await prisma.quiz.findMany({ where: { moduleId: current.moduleId }, orderBy: [{ order: "asc" }, { createdAt: "asc" }] }); const index = items.findIndex((item) => item.id === current.id); const target = index + (req.body.direction === "up" ? -1 : 1); if (target < 0 || target >= items.length) return res.json(current); await prisma.$transaction(async (tx) => { await tx.quiz.update({ where: { id: current.id }, data: { order: -1 } }); await tx.quiz.update({ where: { id: items[target].id }, data: { order: current.order } }); await tx.quiz.update({ where: { id: current.id }, data: { order: items[target].order } }); }); res.json(await prisma.quiz.findUnique({ where: { id: current.id } })); });
r.delete("/:id", requireAuth as any, requireRole("ADMIN", "DOSEN") as any, async (req, res) => { const item = await prisma.quiz.findUnique({ where: { id: req.params.id }, include: { questions: { select: { imageUrl: true } } } }); await prisma.quiz.delete({ where: { id: req.params.id } }); await Promise.all((item?.questions || []).map((question) => removeImageIfUnused(question.imageUrl))); if (item?.moduleId) { const rest = await prisma.quiz.findMany({ where: { moduleId: item.moduleId }, orderBy: [{ order: "asc" }, { createdAt: "asc" }] }); await prisma.$transaction(rest.map((row, index) => prisma.quiz.update({ where: { id: row.id }, data: { order: index + 1 } }))); } res.json({ ok: true }); });

r.post("/:id/start", requireAuth as any, async (req: any, res) => { const quiz = await prisma.quiz.findUnique({ where: { id: req.params.id } }); if (!quiz || quiz.archived || (quiz.deadline && quiz.deadline < new Date())) return res.status(404).json({ message: "Quiz tidak tersedia atau deadline telah lewat." }); if (quiz.attemptLimit === 0) return res.status(403).json({ message: "Quiz ini sedang ditutup." }); const count = await prisma.quizAttempt.count({ where: { userId: req.user.id, quizId: quiz.id, submittedAt: { not: null } } }); if (quiz.attemptLimit > 0 && count >= quiz.attemptLimit) return res.status(400).json({ message: `Batas percobaan ${quiz.attemptLimit} tercapai` }); res.status(201).json(await prisma.quizAttempt.create({ data: { userId: req.user.id, quizId: quiz.id } })); });
r.post("/:id/submit", requireAuth as any, async (req: any, res) => { const parsed = SubmitQuizSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json(parsed.error); const quiz = await prisma.quiz.findUnique({ where: { id: req.params.id }, include: { questions: true } }); if (!quiz) return res.status(404).json({ message: "Not found" }); if (quiz.attemptLimit === 0) return res.status(403).json({ message: "Quiz ini sedang ditutup." }); const last = await prisma.quizAttempt.findFirst({ where: { userId: req.user.id, quizId: quiz.id, submittedAt: null }, orderBy: { startedAt: "desc" } }); const submittedCount = await prisma.quizAttempt.count({ where: { userId: req.user.id, quizId: quiz.id, submittedAt: { not: null } } }); if (!last && quiz.attemptLimit > 0 && submittedCount >= quiz.attemptLimit) return res.status(400).json({ message: `Batas percobaan ${quiz.attemptLimit} tercapai` }); const map = new Map(quiz.questions.map((q) => [q.id, q])); const max = quiz.questions.reduce((s, q) => s + q.points, 0); const score = parsed.data.answers.reduce((s, a) => { const q = map.get(a.questionId); return s + (q && q.correctIndex === a.chosen ? q.points : 0); }, 0); const percent = max ? score / max * 100 : 0; const att = last ? await prisma.quizAttempt.update({ where: { id: last.id }, data: { answers: JSON.stringify(parsed.data.answers), score: percent, passed: percent >= quiz.passingScore, submittedAt: new Date() } }) : await prisma.quizAttempt.create({ data: { userId: req.user.id, quizId: quiz.id, answers: JSON.stringify(parsed.data.answers), score: percent, passed: percent >= quiz.passingScore, submittedAt: new Date() } }); res.json({ ...att, maxScore: max, rawScore: score, answerKey: quiz.showAnswers ? Object.fromEntries(quiz.questions.map((q) => [q.id, q.correctIndex])) : undefined }); });
r.get("/:id/attempts", requireAuth as any, async (req: any, res) => { const where: any = { quizId: req.params.id }; if (req.user.role === "MAHASISWA") where.userId = req.user.id; res.json(await prisma.quizAttempt.findMany({ where, include: { user: { select: { nim: true, name: true } } }, orderBy: { startedAt: "desc" } })); });
r.patch("/:id/deadline", requireAuth as any, requireRole("ADMIN", "DOSEN") as any, async (req, res) => { const deadline = req.body.deadline ? new Date(req.body.deadline) : null; if (deadline && Number.isNaN(deadline.getTime())) return res.status(400).json({ message: "Deadline tidak valid." }); res.json(await prisma.quiz.update({ where: { id: req.params.id }, data: { deadline } })); });

export default r;
