import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";
import { useFeedback } from "../context/FeedbackContext";

export default function AssignmentSubmissions() {
  const { id } = useParams(); const [assignment, setAssignment] = useState<any>(null); const [items, setItems] = useState<any[]>([]); const [drafts, setDrafts] = useState<Record<string, any>>({}); const [error, setError] = useState(""); const { showFeedback } = useFeedback();
  const load = async () => { try { const [assignmentResponse, submissionsResponse] = await Promise.all([api.get(`/api/assignments/${id}`), api.get(`/api/assignments/${id}/submissions`)]); setAssignment(assignmentResponse.data); setItems(Array.isArray(submissionsResponse.data) ? submissionsResponse.data : []); setError(""); } catch (reason: any) { setError(reason?.response?.data?.message || "Submission tidak dapat dimuat."); } };
  useEffect(() => { load(); }, [id]);
  const grade = async (item: any) => { try { await api.patch(`/api/assignments/submissions/${item.id}`, drafts[item.id] || {}); showFeedback("Penilaian tersimpan."); await load(); } catch (reason: any) { showFeedback(reason?.response?.data?.message || "Penilaian gagal disimpan.", "error"); } };
  if (!assignment) return <div className="section-card text-sm text-zinc-500">{error || "Memuat submission..."}</div>;
  return <div className="mx-auto max-w-5xl space-y-6"><Link to="/manage" className="text-sm text-zinc-500">← Kembali ke kelola</Link><div><p className="eyebrow">Penilaian tugas</p><h1 className="mt-2 text-3xl font-bold">{assignment.title}</h1></div><section className="section-card space-y-3"><p className="text-sm text-zinc-500">{items.length} submission masuk</p>{items.map((item) => { const draft = drafts[item.id] || { score: item.score ?? "", feedback: item.feedback || "" }; return <div key={item.id} className="rounded-xl border border-zinc-200 p-4 dark:border-zinc-700"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold">{item.user.name}</p><p className="text-xs text-zinc-500">{item.user.nim} · {new Date(item.submittedAt).toLocaleString()}</p></div>{item.fileUrl && <a className="text-sm text-violet-700 underline" href={`${api.defaults.baseURL || ""}${item.fileUrl}`} target="_blank" rel="noreferrer">Buka lampiran</a>}{item.externalUrl && <a className="text-sm text-violet-700 underline" href={item.externalUrl} target="_blank" rel="noreferrer">Buka link</a>}</div><div className="mt-3 grid gap-3 md:grid-cols-[10rem_1fr_auto]"><label className="block space-y-1 text-sm font-medium">Nilai (0–100)<input className="field" type="number" min="0" max="100" placeholder="Contoh: 85" value={draft.score} onChange={(event) => setDrafts({ ...drafts, [item.id]: { ...draft, score: event.target.value } })} /></label><label className="block space-y-1 text-sm font-medium">Feedback<input className="field" placeholder="Masukan untuk mahasiswa" value={draft.feedback} onChange={(event) => setDrafts({ ...drafts, [item.id]: { ...draft, feedback: event.target.value } })} /></label><button type="button" onClick={() => grade(item)} className="secondary-button self-end">Simpan nilai</button></div></div>; })}{items.length === 0 && <p className="text-sm text-zinc-500">Belum ada pengumpulan.</p>}</section></div>;
}
