import { BookOpen, ChevronDown, Search, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import helpArticles, { type HelpArticle } from "../data/helpArticles";

type Role = "ADMIN" | "DOSEN" | "MAHASISWA";
type Extra = { steps: string[]; troubleshooting?: string[] };

const guidance: Record<string, Extra> = {
  "forgot-password": { steps: ["Minta admin mengatur ulang password jika Anda tidak dapat login.", "Setelah login, buka menu profil dan pilih Ganti password.", "Gunakan password baru minimal 8 karakter, lalu simpan."], troubleshooting: ["Pastikan NIM/identifier diketik persis sesuai akun.", "Jika tetap gagal, minta admin memeriksa status akun dan jangan membagikan password." ] },
  "progress-material": { steps: ["Buka Matkul Saya, lalu pilih mata kuliah dan modul.", "Buka materi melalui tombol akses; video menyimpan progres saat diputar, dijeda, selesai, dan saat halaman ditinggalkan.", "PDF/PPT menyimpan halaman yang dibaca dari server. Buka halaman terakhir agar selesai terbaca."], troubleshooting: ["Membuka halaman tanpa membaca tidak dihitung selesai.", "Jika progres tidak berubah, muat ulang setelah beberapa detik; progres selalu milik akun yang sedang login."] },
  "material-download": { steps: ["Buka materi dari modul yang terdaftar.", "Jika pengelola mewajibkan penyelesaian, selesaikan video atau seluruh halaman PDF/PPT terlebih dahulu.", "Tekan Download setelah status materi menunjukkan selesai."], troubleshooting: ["Materi tertutup, belum masuk jadwal, atau belum selesai akan menampilkan preview dan menolak download.", "Jangan mengubah URL file secara manual; minta dosen/admin memeriksa aturan materi."] },
  assignments: { steps: ["Buka tugas dari modul yang sesuai.", "Periksa jadwal buka, deadline, dan format yang diterima.", "Serahkan file aman atau link HTTPS, kemudian pastikan status submission tersimpan."], troubleshooting: ["Setelah deadline, submission baru ditolak tetapi riwayat lama tetap terlihat.", "Link harus dapat diakses penilai; gunakan izin berbagi Drive yang benar."] },
  "quiz-basics": { steps: ["Buka quiz ketika jadwalnya tersedia.", "Jawab pilihan ganda atau tulis essay, lalu tekan Kirim jawaban.", "Periksa riwayat attempt dan tunggu publikasi nilai bila hasil belum dirilis."], troubleshooting: ["Attempt 0 berarti quiz ditutup; -1 berarti tidak terbatas; angka positif adalah batas maksimum.", "Jadwal buka, deadline, archive, dan timer divalidasi oleh waktu server."] },
  "timer-modes": { steps: ["Periksa mode timer pada instruksi quiz/ujian.", "Timer independen berjalan dari saat attempt dimulai.", "Timer serentak berakhir mengikuti batas jadwal global jika batas itu lebih cepat."], troubleshooting: ["Deadline adalah batas akhir akses/pengumpulan, sedangkan timer adalah durasi attempt.", "Jika halaman tertutup, buka kembali selama attempt masih valid; jangan mengandalkan jam perangkat."] },
  results: { steps: ["Dosen/admin buka Kelola → pilih mata kuliah → pilih modul → section Quiz atau Bank soal.", "Edit quiz dan pada Publikasi nilai pilih Manual, lalu tekan Simpan.", "Kembali ke daftar quiz; tekan Publikasikan hasil pada item berstatus Manual. Untuk UTS/UAS, tombol berada di Bank soal modul ujian.", "Mahasiswa baru melihat nilai setelah hasil dipublikasikan. Mode Terjadwal akan merilis otomatis."], troubleshooting: ["Jika tombol belum terlihat, pastikan quiz tersimpan dengan mode Manual dan pengguna memiliki role ADMIN/DOSEN.", "HIDDEN tidak menampilkan hasil kepada mahasiswa sampai hasil dipublikasikan."] },
  grading: { steps: ["Dosen/admin buka Rekap dan pilih mahasiswa untuk melihat progress, submission, attempt, dan feedback.", "Buka attempt essay, beri skor per jawaban, tambahkan feedback, lalu simpan.", "Publikasikan hasil quiz bila nilai sudah siap dilihat mahasiswa."], troubleshooting: ["Essay yang belum dinilai belum dihitung sebagai nilai final.", "Dosen hanya dapat menilai mahasiswa dari mata kuliah yang ditugaskan."] },
  troubleshooting: { steps: ["Catat URL, role, waktu kejadian, dan pesan error tanpa password/token.", "Periksa jadwal, akses mata kuliah, status archive, dan koneksi API.", "Jika masalah berlanjut, kirim detail tersebut kepada admin."], troubleshooting: ["Error 403 biasanya berarti role, enrollment, assignment, jadwal, atau status konten tidak mengizinkan operasi.", "Error 400 biasanya berarti input tidak memenuhi validasi.", "Error 5xx perlu diperiksa admin melalui log API, database, storage, dan health check."] },
  "getting-started": { steps: ["Buka alamat OMNI dan masukkan NIM/identifier serta password.", "Setelah login, gunakan Dashboard untuk ringkasan dan Matkul Saya untuk belajar.", "Buka card mata kuliah, pilih modul, lalu pilih aktivitas.", "Gunakan Help/Panduan untuk mencari artikel dan tombol Keluar setelah selesai."], troubleshooting: ["Jika login gagal, periksa identifier, password, dan status akun.", "Jika menu tidak muncul, role akun menentukan kewenangan yang tersedia."] },
  "account-password": { steps: ["Buka panel Akun aktif dan pilih Ganti password.", "Isi password saat ini bila diminta, lalu masukkan password baru dan konfirmasi.", "Gunakan 8–128 karakter; pilih kombinasi yang tidak mudah ditebak.", "Tekan Simpan dan login kembali jika sesi berakhir."], troubleshooting: ["Password tidak boleh kosong, kurang dari 8 karakter, atau lebih dari 128 karakter.", "Jika lupa password, ADMIN harus mengatur ulang dari Kelola User."] },
  courses: { steps: ["Mahasiswa buka Matkul Saya; dosen/admin buka Matkul atau Kelola.", "Gunakan card, bukan menebak URL mata kuliah.", "Pilih card untuk melihat modul dan pilih aktivitas yang tersedia.", "Jika daftar kosong, pastikan enrollment atau assignment sudah dibuat."], troubleshooting: ["Mahasiswa yang belum terdaftar akan melihat akses ditolak.", "Dosen hanya melihat mata kuliah yang ditugaskan; pembuatan mata kuliah hanya untuk admin."] },
  "manage-material": { steps: ["Buka Kelola → pilih mata kuliah → pilih modul reguler → Materi.", "Tekan Tambah materi atau Edit pada item yang sudah ada.", "Isi label setiap field, pilih tipe sumber, atur buka manual/jadwal, dan simpan.", "Gunakan Arsipkan/Pulihkan atau tombol naik/turun untuk merapikan daftar."], troubleshooting: ["Materi UTS/UAS tidak menerima materi; pilih modul reguler.", "Upload ditolak jika ukuran, MIME, atau ekstensi tidak aman."] },
  "file-safety": { steps: ["Gunakan tipe file yang memang dibutuhkan tugas dan ukurannya masih di bawah batas aplikasi.", "Untuk file besar, pilih pengumpulan melalui link HTTPS.", "Pastikan link Drive dapat dilihat dosen/admin tanpa meminta akses tambahan.", "Jangan mengunggah executable, script, archive mencurigakan, atau file yang menyamarkan ekstensi."], troubleshooting: ["Error upload biasanya disebabkan ukuran atau MIME type tidak sesuai.", "Jika link tidak terbuka, ubah permission menjadi dapat dilihat dan kirim ulang link."] },
  "content-availability": { steps: ["Dosen/admin buka Edit pada materi, tugas, atau quiz.", "Aktifkan/nonaktifkan Buka untuk mahasiswa untuk kontrol manual.", "Isi Jadwal mulai dan Jadwal akses berakhir jika diperlukan; kosong berarti tidak dibatasi.", "Simpan dan uji dari akun mahasiswa untuk memastikan preview serta status tampil benar."], troubleshooting: ["Deadline berbeda dari Jadwal akses berakhir: deadline menutup aksi, sedangkan jadwal menutup akses isi.", "Archive menyembunyikan item dari mahasiswa dan tidak sama dengan menutup manual."] },
  "exam-modules": { steps: ["Admin/dosen buka Kelola → mata kuliah → Tambah modul UTS atau Tambah modul UAS.", "Buka card modul ujian dan isi passing score, attempt, timer, jadwal, randomisasi, dan publikasi.", "Tambah soal satu per satu atau impor template Excel dari Bank soal.", "Periksa attempt, nilai essay, lalu publikasikan hasil secara manual atau terjadwal."], troubleshooting: ["Satu mata kuliah hanya memiliki satu modul UTS dan satu UAS; gunakan modul susulan bila tersedia.", "Modul ujian tidak dapat dibuatkan materi atau tugas karena hanya untuk bank soal."] },
  "quiz-import": { steps: ["Buka modul reguler atau modul UTS/UAS yang benar.", "Tekan Download template soal dan jangan mengubah nama header.", "Isi metadata quiz pada setiap baris, gunakan || untuk options, dan isi questionType.", "Untuk essay kosongkan options/correctIndex; untuk pilihan ganda isi minimal dua opsi dan correctIndex yang valid.", "Impor .xlsx, baca nomor baris error, perbaiki, lalu ulangi."], troubleshooting: ["Import bersifat transaksi: satu baris invalid membatalkan semua baris.", "UTS/UAS mengambil jenis dari modul; kolom kind tidak digunakan pada template ujian."] },
  "question-images": { steps: ["Pada editor soal pilih upload gambar atau isi URL gambar HTTPS.", "Pastikan gambar jelas, berukuran wajar, dan dapat diakses aplikasi.", "Simpan soal lalu cek preview dari sisi mahasiswa.", "Saat mengganti atau menghapus gambar, sistem membersihkan attachment yang tidak lagi direferensikan."], troubleshooting: ["URL privat atau URL non-HTTPS dapat gagal dimuat.", "Jangan memasukkan URL storage internal atau file executable sebagai gambar."] },
  "student-progress": { steps: ["Dosen/admin buka Rekap dan pilih mata kuliah yang berwenang.", "Cari mahasiswa berdasarkan nama/NIM lalu klik baris atau Lihat detail.", "Periksa progress materi, download, submission, attempt, nilai, feedback, dan status essay.", "Gunakan filter atau export untuk analisis lebih banyak data."], troubleshooting: ["Progress dibaca berdasarkan userId mahasiswa, bukan data global.", "Mahasiswa tidak memiliki akses ke detail rekap mahasiswa lain."] },
  "module-management": { steps: ["Buka Kelola dan pilih card mata kuliah.", "Tambah atau edit modul dari detail mata kuliah; pilih tipe Reguler, UTS, atau UAS.", "Klik card modul untuk masuk ke halaman khusus modul.", "Kelola tugas, materi, dan quiz hanya dari modul reguler; gunakan Bank soal pada modul ujian."], troubleshooting: ["Jika konten terlihat bercampur, pastikan courseId dan moduleId pada URL benar.", "Gunakan tombol kembali untuk berpindah konteks tanpa kehilangan mata kuliah."] },
  "archive-reorder": { steps: ["Buka section item yang ingin dikelola.", "Tekan naik/turun pada item untuk menukar posisi tanpa hapus-buat ulang.", "Pilih Arsipkan untuk menyembunyikan dari mahasiswa atau Pulihkan untuk mengaktifkan.", "Pilih filter Arsip atau Semua untuk menemukan item lama."], troubleshooting: ["Urutan tugas, materi, quiz, dan modul dikelola terpisah.", "Item archive tetap terlihat bagi admin/dosen tetapi tidak dapat diakses mahasiswa."] },
  "course-users": { steps: ["Buka Kelola → mata kuliah → Kelola pengaturan.", "Buka section yang sesuai dan ketik nama atau NIM/NIDN.", "Pilih hasil dari halaman pencarian; gunakan pagination untuk hasil berikutnya.", "Periksa ringkasan pilihan lalu tekan Simpan pengampu atau Simpan peserta."], troubleshooting: ["Jangan memilih semua hasil sekaligus ketika hanya sebagian yang diperlukan.", "Pilihan yang telah tersimpan tetap dipertahankan saat pencarian berubah."] },
  "user-management": { steps: ["ADMIN buka Kelola User dan cari akun berdasarkan NIM/nama.", "Gunakan Edit untuk mengubah data, Password untuk menetapkan password baru, atau hapus akun lain.", "Periksa role sebelum menyimpan; identifier harus unik.", "Jangan mencoba menghapus akun yang sedang login."], troubleshooting: ["Akun sendiri dilindungi dan tidak dapat dihapus.", "User non-admin tidak dapat membuka operasi administrasi meskipun mengetahui URL endpoint."] },
  roles: { steps: ["Identifikasi role pada panel akun aktif.", "Gunakan Matkul Saya untuk belajar sebagai mahasiswa.", "Gunakan Kelola dan Rekap sebagai dosen hanya pada mata kuliah yang ditugaskan.", "Gunakan Kelola User, assignment, backup, dan restore hanya sebagai admin."], troubleshooting: ["Akses ditolak bukan berarti data hilang; biasanya akun belum di-enroll atau di-assign.", "Minta admin memperbaiki assignment/enrollment, bukan membagikan kredensial."] },
  "backup-restore": { steps: ["ADMIN buka halaman Backup/Restore dan buat ZIP sebelum perubahan besar.", "Simpan backup di lokasi aman dan catat versi serta waktunya.", "Pilih file ZIP saat restore, baca peringatan, lalu jalankan restore.", "Setelah selesai, jalankan health check dan uji login, course, upload, serta quiz."], troubleshooting: ["Restore dapat mengganti data aktif; jangan menutup proses di tengah jalan.", "Pastikan file ZIP resmi, database dapat diakses, dan storage cukup."] },
  storage: { steps: ["Gunakan storage persisten untuk deployment production.", "Upload attachment melalui form aplikasi dan jangan mengedit nama file secara manual.", "Saat menghapus atau mengganti item, sistem memeriksa referensi file sebelum cleanup.", "Lakukan backup database dan storage secara berkala."], troubleshooting: ["Jika file hilang setelah restart, volume/object storage belum dikonfigurasi.", "Jika attachment lama masih ada, admin perlu memeriksa referensi sebelum menghapusnya."] },
  integration: { steps: ["ADMIN siapkan secret server seperti JWT_SECRET dan API key.", "Konfigurasikan origin frontend, SSO, dan endpoint export di environment backend.", "Uji health check dan integrasi dengan akun non-produksi terlebih dahulu.", "Pantau log tanpa mencatat token atau password."], troubleshooting: ["SSO gagal jika token expired, signature salah, atau user tidak aktif.", "Export/API ditolak jika API key salah atau role tidak berwenang."] },
  security: { steps: ["Gunakan password unik dan jangan membagikan token/session.", "Logout dari perangkat bersama dan gunakan HTTPS.", "Upload hanya file aman dan link submission HTTPS.", "Laporkan aktivitas mencurigakan kepada admin."], troubleshooting: ["Jangan mencoba melewati role guard lewat URL atau request manual.", "Jawaban benar, correctIndex, dan data user lain memang tidak dikirim ke mahasiswa."] },
  glossary: { steps: ["Cari istilah yang belum dipahami di kotak pencarian Help.", "Gunakan konteks halaman terkait untuk melihat cara pemakaiannya.", "Baca perbedaan deadline, jadwal akses, timer, attempt, archive, dan publikasi sebelum mengatur evaluasi."], troubleshooting: ["Jika label UI berbeda, gunakan istilah yang terlihat pada form terbaru dan laporkan ketidaksesuaian kepada admin."] },
  faq: { steps: ["Cari pertanyaan dengan kata kunci utama, misalnya download, attempt, atau nilai.", "Buka artikel terkait untuk langkah lengkap, bukan hanya ringkasan FAQ.", "Jika solusi tidak berhasil, catat pesan error dan hubungi admin."], troubleshooting: ["FAQ menjelaskan perilaku umum; keputusan akses tetap ditentukan endpoint dan role akun.", "Untuk masalah nilai, sertakan nama quiz, attempt, dan waktu kejadian tanpa data rahasia."] }
};

function normalize(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
function articleText(article: HelpArticle) { const extra = guidance[article.id]; return normalize([article.title, article.summary, article.category, article.content, ...article.keywords, ...(article.steps || []), ...(extra?.steps || []), ...(extra?.troubleshooting || [])].join(" ")); }

export default function Help() {
  const { user } = useAuth();
  const [params, setParams] = useSearchParams();
  const [query, setQuery] = useState(params.get("q") || "");
  const [category, setCategory] = useState(params.get("category") || "Semua");
  const role = user?.role as Role;
  const selectedId = params.get("article");
  const allowed = useMemo(() => helpArticles.filter((article) => article.roles.includes(role)), [role]);
  const categories = useMemo(() => ["Semua", ...Array.from(new Set(allowed.map((article) => article.category)))], [allowed]);
  const results = useMemo(() => { const terms = normalize(query.trim()).split(/\s+/).filter(Boolean); return allowed.filter((article) => (category === "Semua" || article.category === category) && terms.every((term) => articleText(article).includes(term))); }, [allowed, category, query]);
  const selected = selectedId ? allowed.find((article) => article.id === selectedId) : undefined;
  useEffect(() => { const timer = window.setTimeout(() => { setParams((current) => { const next = new URLSearchParams(current); if (query.trim()) next.set("q", query.trim()); else next.delete("q"); if (category !== "Semua") next.set("category", category); else next.delete("category"); return next; }, { replace: true }); }, 280); return () => window.clearTimeout(timer); }, [query, category, setParams]);
  const openArticle = (article: HelpArticle) => setParams((current) => { const next = new URLSearchParams(current); next.set("article", article.id); return next; });
  const closeArticle = () => setParams((current) => { const next = new URLSearchParams(current); next.delete("article"); return next; });
  const related = selected?.related?.map((id) => allowed.find((article) => article.id === id)).filter(Boolean) as HelpArticle[] | undefined;
  if (selectedId && !selected) return <div className="mx-auto max-w-3xl"><section className="section-card space-y-4"><p className="eyebrow">Akses terbatas</p><h1 className="text-2xl font-bold">Panduan ini tidak tersedia untuk role Anda</h1><p className="text-sm leading-7 text-zinc-500">Artikel yang diminta membutuhkan kewenangan berbeda. Anda tetap dapat mencari panduan untuk role {role}.</p><button type="button" onClick={closeArticle} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">Kembali ke panduan</button></section></div>;
  return <div className="mx-auto max-w-6xl space-y-7"><div><p className="eyebrow">Help center</p><h1 className="mt-2 text-3xl font-bold">Panduan penggunaan OMNI</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">Cari cara memakai fitur, langkah penyelesaian masalah, dan FAQ berdasarkan kewenangan akun Anda.</p></div><section className="section-card space-y-4"><div className="flex items-center gap-3 rounded-xl border border-zinc-200 px-4 dark:border-zinc-700"><Search size={18} className="text-zinc-400" /><input aria-label="Cari dokumentasi" value={query} onChange={(event) => { setQuery(event.target.value); closeArticle(); }} placeholder="Cari panduan, misalnya publikasi manual, timer, import Excel, atau progress..." className="min-h-12 flex-1 bg-transparent text-sm outline-none" /></div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-zinc-500">Kategori:</span>{categories.map((item) => <button type="button" key={item} onClick={() => { setCategory(item); closeArticle(); }} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${category === item ? "bg-violet-100 text-violet-700 dark:bg-violet-950/60 dark:text-violet-200" : "bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300"}`}>{item}</button>)}</div><div className="flex items-center gap-2 text-xs text-zinc-500"><ShieldCheck size={15} className="text-emerald-500" /> Menampilkan {allowed.length} artikel sesuai role {role}. Artikel yang tidak berwenang disembunyikan.</div></section>{selected ? <ArticleDetail article={selected} related={related || []} onBack={closeArticle} onOpen={openArticle} /> : <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-semibold">{query || category !== "Semua" ? "Hasil pencarian" : "Semua panduan"}</h2><span className="text-xs text-zinc-500">{results.length} artikel</span></div>{results.map((article) => <button type="button" key={article.id} onClick={() => openArticle(article)} className="group section-card flex w-full items-start gap-4 text-left transition hover:-translate-y-0.5 hover:border-violet-300"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-100 text-violet-700 dark:bg-violet-950/60 dark:text-violet-200"><BookOpen size={18} /></span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold uppercase tracking-wide text-violet-600">{article.category}</span><span className="mt-1 block font-semibold">{article.title}</span><span className="mt-1 block text-sm leading-6 text-zinc-500">{article.summary}</span></span><ChevronDown size={18} className="mt-1 shrink-0 -rotate-90 text-zinc-400 transition group-hover:text-violet-600" /></button>)}{results.length === 0 && <div className="section-card text-sm text-zinc-500">Tidak ada panduan yang cocok. Coba kata kunci lain, hapus kategori, atau cari istilah lebih umum.</div>}</section>}</div>;
}

function ArticleDetail({ article, related, onBack, onOpen }: { article: HelpArticle; related: HelpArticle[]; onBack: () => void; onOpen: (article: HelpArticle) => void }) { const extra = guidance[article.id]; return <article className="section-card space-y-6"><button type="button" onClick={onBack} className="text-sm font-semibold text-violet-700">← Kembali ke hasil pencarian</button><div><p className="eyebrow">{article.category}</p><h2 className="mt-2 text-2xl font-bold">{article.title}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{article.summary}</p></div>{(article.steps || extra?.steps) && <section className="rounded-2xl border border-violet-100 bg-violet-50/60 p-4 dark:border-violet-900/50 dark:bg-violet-950/20"><h3 className="font-semibold">Cara menggunakan</h3><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-7">{(extra?.steps || article.steps || []).map((step) => <li key={step}>{step}</li>)}</ol></section>}<section><h3 className="font-semibold">Penjelasan</h3><p className="mt-2 whitespace-pre-line text-sm leading-7 text-zinc-700 dark:text-zinc-300">{article.content}</p></section>{extra?.troubleshooting && <section className="rounded-2xl border border-amber-200 bg-amber-50/70 p-4 dark:border-amber-900/50 dark:bg-amber-950/20"><h3 className="font-semibold">Jika mengalami kendala</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-7">{extra.troubleshooting.map((item) => <li key={item}>{item}</li>)}</ul></section>}{related.length > 0 && <section className="border-t border-zinc-200 pt-4 dark:border-zinc-700"><p className="text-sm font-semibold">Panduan terkait</p><div className="mt-2 flex flex-wrap gap-2">{related.map((item) => <button type="button" key={item.id} onClick={() => onOpen(item)} className="rounded-full bg-zinc-100 px-3 py-1.5 text-xs font-semibold text-zinc-700 dark:bg-zinc-800 dark:text-zinc-200">{item.title}</button>)}</div></section>}</article>; }
