import { BookOpen, ChevronDown, Search, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import helpArticles, { type HelpArticle } from "../data/helpArticles";

type Role = "ADMIN" | "DOSEN" | "MAHASISWA";
type Extra = { steps: string[]; troubleshooting?: string[] };

const guidance: Record<string, Extra> = {
  "forgot-password": { steps: ["Minta admin mengatur ulang password jika Anda tidak dapat login.", "Setelah login, buka menu profil dan pilih Ganti password.", "Gunakan password baru minimal 8 karakter, lalu simpan."], troubleshooting: ["Pastikan NIM/identifier diketik persis sesuai akun.", "Jika tetap gagal, minta admin memeriksa status akun dan jangan membagikan password." ] },
  "progress-material": { steps: ["Buka Matkul Saya, lalu pilih mata kuliah dan modul.", "Buka materi melalui tombol akses; video menyimpan progres saat diputar, dijeda, selesai, dan saat halaman ditinggalkan.", "PDF/PPT menyimpan halaman yang dibaca dari server. Buka halaman terakhir agar selesai terbaca."], troubleshooting: ["Membuka halaman tanpa membaca tidak dihitung selesai.", "Jika progres tidak berubah, muat ulang setelah beberapa detik; progres selalu milik akun yang sedang login."] },
  "material-download": { steps: ["Buka materi dari modul yang terdaftar.", "Jika pengelola mewajibkan penyelesaian, selesaikan video atau seluruh halaman PDF/PPT terlebih dahulu.", "Tekan Download setelah status materi menunjukkan selesai."], troubleshooting: ["Materi tertutup, belum masuk jadwal, atau belum selesai akan menampilkan preview dan menolak download.", "Jangan mengubah URL file secara manual; minta dosen/admin memeriksa aturan materi."] },
  assignments: { steps: ["Buka tugas dari modul yang sesuai.", "Periksa jadwal buka, deadline, dan format yang diterima.", "Serahkan file aman atau link HTTPS, kemudian pastikan status submission tersimpan."], troubleshooting: ["Setelah deadline, submission baru ditolak tetapi riwayat lama tetap terlihat.", "Link harus dapat diakses penilai; gunakan izin berbagi Drive yang benar."] },
  "quiz-basics": { steps: ["Buka quiz ketika jadwalnya tersedia.", "Jawab pilihan ganda atau tulis essay, lalu tekan Kirim jawaban.", "Periksa riwayat attempt dan tunggu publikasi nilai bila hasil belum dirilis."], troubleshooting: ["Attempt 0 berarti quiz ditutup; -1 berarti tidak terbatas; angka positif adalah batas maksimum.", "Jadwal buka, deadline, archive, dan timer divalidasi oleh waktu server."] },
  "timer-modes": { steps: ["Periksa mode timer pada instruksi quiz/ujian.", "Timer independen berjalan dari saat attempt dimulai.", "Timer serentak berakhir mengikuti batas jadwal global jika batas itu lebih cepat."], troubleshooting: ["Deadline adalah batas akhir akses/pengumpulan, sedangkan timer adalah durasi attempt.", "Jika halaman tertutup, buka kembali selama attempt masih valid; jangan mengandalkan jam perangkat."] },
  results: { steps: ["Dosen/admin buka Kelola → pilih mata kuliah → pilih modul → section Quiz atau Bank soal.", "Edit quiz dan pada Publikasi nilai pilih Manual, lalu tekan Simpan.", "Kembali ke daftar quiz; tekan Publikasikan hasil pada item berstatus Manual. Untuk UTS/UAS, tombol berada di Bank soal modul ujian.", "Mahasiswa baru melihat nilai setelah hasil dipublikasikan. Mode Terjadwal akan merilis otomatis."], troubleshooting: ["Jika tombol belum terlihat, pastikan quiz tersimpan dengan mode Manual dan pengguna memiliki role ADMIN/DOSEN.", "HIDDEN tidak menampilkan hasil kepada mahasiswa sampai hasil dipublikasikan."] },
  "quiz-import": { steps: ["Buka modul dan tekan Download template soal.", "Isi satu baris untuk setiap soal; options memakai pemisah ||.", "Pilih MULTIPLE_CHOICE atau ESSAY, isi correctIndex hanya untuk pilihan ganda, lalu impor .xlsx.", "Jika ada baris invalid, perbaiki nomor baris yang dilaporkan dan impor ulang; transaksi tidak menyimpan data parsial."], troubleshooting: ["Pastikan module merujuk modul yang sedang dikelola dan URL gambar menggunakan HTTPS.", "Jangan mengubah nama header template atau delimiter options."] },
  grading: { steps: ["Dosen/admin buka Rekap dan pilih mahasiswa untuk melihat progress, submission, attempt, dan feedback.", "Buka attempt essay, beri skor per jawaban, tambahkan feedback, lalu simpan.", "Publikasikan hasil quiz bila nilai sudah siap dilihat mahasiswa."], troubleshooting: ["Essay yang belum dinilai belum dihitung sebagai nilai final.", "Dosen hanya dapat menilai mahasiswa dari mata kuliah yang ditugaskan."] },
  "course-users": { steps: ["Buka Kelola → pilih mata kuliah → Kelola pengaturan.", "Buka section Dosen pengampu atau Mahasiswa terdaftar.", "Cari berdasarkan nama atau NIM/NIDN, pilih hasil, lalu simpan assignment."], troubleshooting: ["Hasil dibatasi per halaman agar tetap ringan. Gunakan halaman berikutnya atau kata kunci lebih spesifik.", "Pilihan tersimpan tetap dipertahankan walau tidak cocok dengan pencarian aktif."] },
  "backup-restore": { steps: ["Admin buka Backup/Restore dan buat backup ZIP.", "Simpan ZIP di lokasi aman bersama catatan waktu backup.", "Untuk restore, pilih ZIP yang valid, tinjau peringatan, lalu jalankan restore dan cek health check."], troubleshooting: ["Restore memerlukan role ADMIN dan backup yang tidak rusak.", "Backup production sebaiknya disimpan di storage terpisah dan diuji berkala."] },
  troubleshooting: { steps: ["Catat URL, role, waktu kejadian, dan pesan error tanpa password/token.", "Periksa jadwal, akses mata kuliah, status archive, dan koneksi API.", "Jika masalah berlanjut, kirim detail tersebut kepada admin."], troubleshooting: ["Error 403 biasanya berarti role, enrollment, assignment, jadwal, atau status konten tidak mengizinkan operasi.", "Error 400 biasanya berarti input tidak memenuhi validasi.", "Error 5xx perlu diperiksa admin melalui log API, database, storage, dan health check."] }
};

function normalize(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
function articleText(article: HelpArticle) { const extra = guidance[article.id]; return normalize([article.title, article.summary, article.category, article.content, ...article.keywords, ...(article.steps || []), ...(extra?.steps || []), ...(extra?.troubleshooting || [])].join(" ")); }

export default function Help() {
  const { user } = useAuth();
  const [params, setParams] = useSearchParams();
  const [query, setQuery] = useState(params.get("q") || "");
  const [category, setCategory] = useState(params.get("category") || "Semua");
  const role = user?.role as Role;
  const selectedId = params.get("article");
  const allowed = useMemo(() => helpArticles.filter((article) => article.roles.includes(role)), [role]);
  const categories = useMemo(() => ["Semua", ...Array.from(new Set(allowed.map((article) => article.category)))], [allowed]);
  const results = useMemo(() => { const terms = normalize(query.trim()).split(/\s+/).filter(Boolean); return allowed.filter((article) => (category === "Semua" || article.category === category) && terms.every((term) => articleText(article).includes(term))); }, [allowed, category, query]);
  const selected = selectedId ? allowed.find((article) => article.id === selectedId) : undefined;
  useEffect(() => { const timer = window.setTimeout(() => { setParams((current) => { const next = new URLSearchParams(current); if (query.trim()) next.set("q", query.trim()); else next.delete("q"); if (category !== "Semua") next.set("category", category); else next.delete("category"); next.delete("article"); return next; }, { replace: true }); }, 280); return () => window.clearTimeout(timer); }, [query, category, setParams]);
  const openArticle = (article: HelpArticle) => setParams((current) => { const next = new URLSearchParams(current); next.set("article", article.id); return next; });
  const closeArticle = () => setParams((current) => { const next = new URLSearchParams(current); next.delete("article"); return next; });
  const related = selected?.related?.map((id) => allowed.find((article) => article.id === id)).filter(Boolean) as HelpArticle[] | undefined;
  if (selectedId && !selected) return <div className="mx-auto max-w-3xl"><section className="section-card space-y-4"><p className="eyebrow">Akses terbatas</p><h1 className="text-2xl font-bold">Panduan ini tidak tersedia untuk role Anda</h1><p className="text-sm leading-7 text-zinc-500">Artikel yang diminta membutuhkan kewenangan berbeda. Anda tetap dapat mencari panduan untuk role {role}.</p><button type="button" onClick={closeArticle} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">Kembali ke panduan</button></section></div>;
  return <div className="mx-auto max-w-6xl space-y-7"><div><p className="eyebrow">Help center</p><h1 className="mt-2 text-3xl font-bold">Panduan penggunaan OMNI</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">Cari cara memakai fitur, langkah penyelesaian masalah, dan FAQ berdasarkan kewenangan akun Anda.</p></div><section className="section-card space-y-4"><div className="flex items-center gap-3 rounded-xl border border-zinc-200 px-4 dark:border-zinc-700"><Search size={18} className="text-zinc-400" /><input aria-label="Cari dokumentasi" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari panduan, misalnya publikasi manual, timer, import Excel, atau progress..." className="min-h-12 flex-1 bg-transparent text-sm outline-none" /></div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-zinc-500">Kategori:</span>{categories.map((item) => <button type="button" key={item} onClick={() => setCategory(item)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${category === item ? "bg-violet-100 text-violet-700 dark:bg-violet-950/60 dark:text-violet-200" : "bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300"}`}>{item}</button>)}</div><div className="flex items-center gap-2 text-xs text-zinc-500"><ShieldCheck size={15} className="text-emerald-500" /> Menampilkan {allowed.length} artikel sesuai role {role}. Artikel yang tidak berwenang disembunyikan.</div></section>{selected ? <ArticleDetail article={selected} related={related || []} onBack={closeArticle} onOpen={openArticle} /> : <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-semibold">{query || category !== "Semua" ? "Hasil pencarian" : "Semua panduan"}</h2><span className="text-xs text-zinc-500">{results.length} artikel</span></div>{results.map((article) => <button type="button" key={article.id} onClick={() => openArticle(article)} className="group section-card flex w-full items-start gap-4 text-left transition hover:-translate-y-0.5 hover:border-violet-300"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-100 text-violet-700 dark:bg-violet-950/60 dark:text-violet-200"><BookOpen size={18} /></span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold uppercase tracking-wide text-violet-600">{article.category}</span><span className="mt-1 block font-semibold">{article.title}</span><span className="mt-1 block text-sm leading-6 text-zinc-500">{article.summary}</span></span><ChevronDown size={18} className="mt-1 shrink-0 -rotate-90 text-zinc-400 transition group-hover:text-violet-600" /></button>)}{results.length === 0 && <div className="section-card text-sm text-zinc-500">Tidak ada panduan yang cocok. Coba kata kunci lain, hapus kategori, atau cari istilah lebih umum.</div>}</section>}</div>;
}

function ArticleDetail({ article, related, onBack, onOpen }: { article: HelpArticle; related: HelpArticle[]; onBack: () => void; onOpen: (article: HelpArticle) => void }) { const extra = guidance[article.id]; return <article className="section-card space-y-6"><button type="button" onClick={onBack} className="text-sm font-semibold text-violet-700">← Kembali ke hasil pencarian</button><div><p className="eyebrow">{article.category}</p><h2 className="mt-2 text-2xl font-bold">{article.title}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{article.summary}</p></div>{(article.steps || extra?.steps) && <section className="rounded-2xl border border-violet-100 bg-violet-50/60 p-4 dark:border-violet-900/50 dark:bg-violet-950/20"><h3 className="font-semibold">Cara menggunakan</h3><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-7">{(extra?.steps || article.steps || []).map((step) => <li key={step}>{step}</li>)}</ol></section>}<section><h3 className="font-semibold">Penjelasan</h3><p className="mt-2 whitespace-pre-line text-sm leading-7 text-zinc-700 dark:text-zinc-300">{article.content}</p></section>{extra?.troubleshooting && <section className="rounded-2xl border border-amber-200 bg-amber-50/70 p-4 dark:border-amber-900/50 dark:bg-amber-950/20"><h3 className="font-semibold">Jika mengalami kendala</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-7">{extra.troubleshooting.map((item) => <li key={item}>{item}</li>)}</ul></section>}{related.length > 0 && <section className="border-t border-zinc-200 pt-4 dark:border-zinc-700"><p className="text-sm font-semibold">Panduan terkait</p><div className="mt-2 flex flex-wrap gap-2">{related.map((item) => <button type="button" key={item.id} onClick={() => onOpen(item)} className="rounded-full bg-zinc-100 px-3 py-1.5 text-xs font-semibold text-zinc-700 dark:bg-zinc-800 dark:text-zinc-200">{item.title}</button>)}</div></section>}</article>; }
