import { BookOpen, ChevronDown, Search, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import helpArticles, { type HelpArticle } from "../data/helpArticles";

export default function Help() {
  const { user } = useAuth();
  const [params, setParams] = useSearchParams();
  const [query, setQuery] = useState(params.get("q") || "");
  const [category, setCategory] = useState(params.get("category") || "Semua");
  const selectedId = params.get("article");
  const role = user?.role as "ADMIN" | "DOSEN" | "MAHASISWA";
  const allowed = useMemo(() => helpArticles.filter((article) => article.roles.includes(role)), [role]);
  const categories = useMemo(() => ["Semua", ...Array.from(new Set(allowed.map((article) => article.category)))], [allowed]);
  const results = useMemo(() => { const needle = query.trim().toLowerCase(); return allowed.filter((article) => (category === "Semua" || article.category === category) && (!needle || [article.title, article.summary, article.category, article.content, ...article.keywords].join(" ").toLowerCase().includes(needle))); }, [allowed, category, query]);
  const selected = selectedId ? allowed.find((article) => article.id === selectedId) : undefined;
  const inaccessible = Boolean(selectedId && !selected);

  useEffect(() => { const timer = window.setTimeout(() => { const next = new URLSearchParams(params); if (query.trim()) next.set("q", query.trim()); else next.delete("q"); if (category !== "Semua") next.set("category", category); else next.delete("category"); setParams(next, { replace: true }); }, 280); return () => window.clearTimeout(timer); }, [query, category]);

  const openArticle = (article: HelpArticle) => { const next = new URLSearchParams(params); next.set("article", article.id); setParams(next); };
  const closeArticle = () => { const next = new URLSearchParams(params); next.delete("article"); setParams(next); };
  const related = selected?.related?.map((id) => allowed.find((article) => article.id === id)).filter(Boolean) as HelpArticle[] | undefined;

  if (inaccessible) return <div className="mx-auto max-w-3xl"><section className="section-card space-y-4"><p className="eyebrow">Akses terbatas</p><h1 className="text-2xl font-bold">Panduan ini tidak tersedia untuk role Anda</h1><p className="text-sm leading-7 text-zinc-500">Artikel yang diminta membutuhkan kewenangan berbeda. Anda tetap dapat mencari panduan yang tersedia untuk role {role}.</p><button onClick={() => { const next = new URLSearchParams(params); next.delete("article"); setParams(next); }} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">Kembali ke panduan</button></section></div>;

  return <div className="mx-auto max-w-6xl space-y-7"><div><p className="eyebrow">Help center</p><h1 className="mt-2 text-3xl font-bold">Panduan penggunaan OMNI</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">Cari panduan berdasarkan fitur, role, atau masalah yang sedang Anda hadapi.</p></div><section className="section-card space-y-4"><div className="flex items-center gap-3 rounded-xl border border-zinc-200 px-4 dark:border-zinc-700"><Search size={18} className="text-zinc-400" /><input aria-label="Cari dokumentasi" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari panduan, misalnya timer, import Excel, atau progress..." className="min-h-12 flex-1 bg-transparent text-sm outline-none" /></div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-zinc-500">Kategori:</span>{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${category === item ? "bg-violet-100 text-violet-700 dark:bg-violet-950/60 dark:text-violet-200" : "bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300"}`}>{item}</button>)}</div><div className="flex items-center gap-2 text-xs text-zinc-500"><ShieldCheck size={15} className="text-emerald-500" /> Menampilkan {allowed.length} artikel yang sesuai untuk role {role}.</div></section>{selected ? <ArticleDetail article={selected} related={related || []} onBack={closeArticle} onOpen={openArticle} /> : <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-semibold">{query || category !== "Semua" ? "Hasil pencarian" : "Semua panduan"}</h2><span className="text-xs text-zinc-500">{results.length} artikel</span></div>{results.map((article) => <button key={article.id} onClick={() => openArticle(article)} className="group section-card flex w-full items-start gap-4 text-left transition hover:-translate-y-0.5 hover:border-violet-300"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-100 text-violet-700 dark:bg-violet-950/60 dark:text-violet-200"><BookOpen size={18} /></span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold uppercase tracking-wide text-violet-600">{article.category}</span><span className="mt-1 block font-semibold">{article.title}</span><span className="mt-1 block text-sm leading-6 text-zinc-500">{article.summary}</span></span><ChevronDown size={18} className="mt-1 shrink-0 -rotate-90 text-zinc-400 transition group-hover:text-violet-600" /></button>)}{results.length === 0 && <div className="section-card text-sm text-zinc-500">Tidak ada panduan yang cocok. Coba kata kunci atau kategori lain.</div>}</section>}</div>;
}

function ArticleDetail({ article, related, onBack, onOpen }: { article: HelpArticle; related: HelpArticle[]; onBack: () => void; onOpen: (article: HelpArticle) => void }) { return <article className="section-card space-y-5"><button onClick={onBack} className="text-sm font-semibold text-violet-700">← Kembali ke hasil pencarian</button><div><p className="eyebrow">{article.category}</p><h2 className="mt-2 text-2xl font-bold">{article.title}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{article.summary}</p></div>{article.steps && <ol className="list-decimal space-y-2 pl-5 text-sm leading-6">{article.steps.map((step) => <li key={step}>{step}</li>)}</ol>}<p className="whitespace-pre-line text-sm leading-7 text-zinc-700 dark:text-zinc-300">{article.content}</p>{related.length > 0 && <div className="border-t border-zinc-200 pt-4 dark:border-zinc-700"><p className="text-sm font-semibold">Panduan terkait</p><div className="mt-2 flex flex-wrap gap-2">{related.map((item) => <button key={item.id} onClick={() => onOpen(item)} className="rounded-full bg-zinc-100 px-3 py-1.5 text-xs font-semibold text-zinc-700 dark:bg-zinc-800 dark:text-zinc-200">{item.title}</button>)}</div></div>}</article>; }
