import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, CirclePlay, Download, FileText, XCircle } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";

export default function StudentProgress() {
  const { courseId, studentId } = useParams(); const [data, setData] = useState<any>(null); const [error, setError] = useState("");
  useEffect(() => { api.get(`/api/progress/rekap/${courseId}/student/${studentId}`).then((r) => setData(r.data)).catch(() => setError("Data mahasiswa belum dapat dimuat.")); }, [courseId, studentId]);
  const videos = useMemo(() => new Map((data?.progress?.videos || []).map((item: any) => [item.materialId, item.percent])), [data]); const slides = useMemo(() => new Map((data?.progress?.slides || []).map((item: any) => [item.materialId, item.percent])), [data]);
  if (error) return <div className="section-card">{error}</div>; if (!data) return <div className="section-card">Memuat data mahasiswa...</div>;
  const regular = data.modules.filter((module: any) => !["UTS", "UAS"].includes(module.type)); const exams = data.modules.filter((module: any) => ["UTS", "UAS"].includes(module.type));
  return <div className="mx-auto max-w-6xl space-y-7"><Link to={`/rekap?courseId=${courseId}`} className="secondary-button w-fit"><ArrowLeft size={16} /> Kembali ke rekap</Link><div><p className="eyebrow">Penilaian mahasiswa</p><h1 className="mt-2 text-3xl font-bold">{data.student.name}</h1><p className="mt-2 text-sm text-zinc-500">{data.student.nim} · {data.course.title}</p></div><div className="grid gap-4 sm:grid-cols-4"><Stat label="Video" value={data.progress.videos.length} icon={<CirclePlay size={17} />} /><Stat label="Slide/PDF" value={data.progress.slides.length} icon={<FileText size={17} />} /><Stat label="Download" value={data.progress.downloads.length} icon={<Download size={17} />} /><Stat label="Attempt evaluasi" value={data.attempts.length} icon={<CheckCircle2 size={17} />} /></div><QuizSection title="Hasil Quiz, Pretest, dan Posttest" modules={regular} attempts={data.attempts} /><ExamSection modules={exams} attempts={data.attempts} /><AssignmentSection modules={regular} submissions={data.assignmentSubmissions || []} /><MaterialSection modules={regular} videos={videos} slides={slides} /></div>;
}

function QuizSection({ title, modules, attempts }: any) { return <section className="section-card space-y-4"><h2 className="font-semibold">{title}</h2>{modules.map((module: any) => <div key={module.id} className="space-y-2"><h3 className="text-sm font-semibold text-violet-700">{module.title}</h3>{module.quizzes.map((quiz: any) => <QuizResult key={quiz.id} quiz={quiz} attempts={attempts.filter((attempt: any) => attempt.quizId === quiz.id)} />)}</div>)}{modules.every((module: any) => !module.quizzes.length) && <p className="text-sm text-zinc-500">Belum ada Quiz reguler.</p>}</section>; }
function ExamSection({ modules, attempts }: any) { return <section className="section-card space-y-4"><div><h2 className="font-semibold">Hasil UTS dan UAS</h2><p className="mt-1 text-sm text-zinc-500">Rekap ujian khusus ditampilkan terpisah dari Quiz reguler.</p></div>{modules.map((module: any) => <div key={module.id} className="space-y-2"><h3 className="text-sm font-semibold text-violet-700">{module.type} · {module.title}</h3>{module.quizzes.map((quiz: any) => <QuizResult key={quiz.id} quiz={quiz} attempts={attempts.filter((attempt: any) => attempt.quizId === quiz.id)} />)}</div>)}{modules.length === 0 && <p className="text-sm text-zinc-500">Belum ada modul UTS atau UAS.</p>}</section>; }
function QuizResult({ quiz, attempts }: any) { return <div className="rounded-xl border border-zinc-200 p-4 dark:border-zinc-700"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold">{quiz.title}</p><p className="text-xs text-zinc-500">{attempts.length} attempt · passing {quiz.passingScore}%</p></div>{attempts.length === 0 ? <span className="text-xs text-zinc-500">Belum dikerjakan</span> : <span className="text-sm font-bold">Terbaik: {Math.max(...attempts.map((attempt: any) => Math.round(attempt.score)))}%</span>}</div>{attempts.map((attempt: any) => <div key={attempt.id} className="mt-3 rounded-lg bg-zinc-50 p-3 text-sm dark:bg-zinc-800/70"><div className="flex items-center justify-between"><span>{new Date(attempt.submittedAt || attempt.startedAt).toLocaleString()}</span><span className={attempt.passed ? "text-emerald-600" : "text-red-600"}>{Math.round(attempt.score)}% {attempt.passed ? <CheckCircle2 className="inline" size={15} /> : <XCircle className="inline" size={15} />}</span></div><div className="mt-2 space-y-2 text-xs text-zinc-600 dark:text-zinc-300">{quiz.questions.map((question: any) => <QuestionResult key={question.id} attempt={attempt} question={question} />)}</div></div>)}</div>; }
function QuestionResult({ attempt, question }: any) { let answers: any[] = []; try { answers = JSON.parse(attempt.answers || "[]"); } catch {} const answer = answers.find((item) => item.questionId === question.id); return <div><p className="font-semibold">{question.text}</p>{question.type === "ESSAY" ? <EssayGrade attemptId={attempt.id} question={question} answer={answer} existing={attempt.answerGrades?.find((grade: any) => grade.questionId === question.id)} /> : <p>Jawaban: {answer ? question.options[answer.chosen] || "Tidak valid" : "Tidak dijawab"} · Kunci: {question.options[question.correctIndex]} · {question.points} poin</p>}</div>; }
function AssignmentSection({ modules, submissions }: any) { return <section className="section-card space-y-4"><h2 className="font-semibold">Pengumpulan tugas</h2>{modules.map((module: any) => <div key={module.id}><h3 className="text-sm font-semibold text-violet-700">{module.title}</h3><div className="mt-2 space-y-2">{module.assignments.map((assignment: any) => { const submission = submissions.find((item: any) => item.assignmentId === assignment.id); return <div key={assignment.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-zinc-50 p-3 text-sm dark:bg-zinc-800/70"><span>{assignment.title}</span>{submission ? <span className="font-semibold">{submission.score === null ? "Belum dinilai" : `${submission.score}/100`}</span> : <span className="text-zinc-500">Belum dikumpulkan</span>}</div>; })}</div></div>)}{modules.every((module: any) => !module.assignments.length) && <p className="text-sm text-zinc-500">Belum ada tugas reguler.</p>}</section>; }
function MaterialSection({ modules, videos, slides }: any) { return <section className="section-card space-y-4"><h2 className="font-semibold">Progress materi</h2>{modules.map((module: any) => <div key={module.id}><h3 className="text-sm font-semibold text-violet-700">{module.title}</h3><div className="mt-2 space-y-2">{module.materials.map((material: any) => { const percent = material.type === "VIDEO" ? videos.get(material.id) || 0 : slides.get(material.id) || 0; return <div key={material.id} className="flex items-center justify-between rounded-lg bg-zinc-50 p-3 text-sm dark:bg-zinc-800/70"><span>{material.title}</span><span className="font-semibold">{Math.round(percent)}%</span></div>; })}</div></div>)}{modules.every((module: any) => !module.materials.length) && <p className="text-sm text-zinc-500">Belum ada materi reguler.</p>}</section>; }
function EssayGrade({ attemptId, question, answer, existing }: any) { const [score, setScore] = useState(existing?.score ?? ""); const [feedback, setFeedback] = useState(existing?.feedback || ""); const [saving, setSaving] = useState(false); const save = async () => { setSaving(true); try { await api.patch(`/api/quizzes/attempts/${attemptId}/questions/${question.id}/grade`, { score, feedback }); } finally { setSaving(false); } }; return <div className="mt-2 space-y-2"><p>Jawaban essay: {answer?.answerText || "Tidak dijawab"}</p><div className="flex flex-wrap gap-2"><input className="field w-28" type="number" min="0" max={question.points} placeholder={`Nilai / ${question.points}`} value={score} onChange={(e) => setScore(e.target.value)} /><input className="field min-w-56 flex-1" placeholder="Feedback" value={feedback} onChange={(e) => setFeedback(e.target.value)} /><button onClick={save} disabled={saving} className="secondary-button">{saving ? "Menyimpan..." : "Nilai essay"}</button></div></div>; }
function Stat({ label, value, icon }: any) { return <div className="section-card"><div className="flex items-center gap-2 text-violet-600">{icon}<span className="text-xs text-zinc-500">{label}</span></div><p className="mt-2 text-2xl font-bold">{value}</p></div>; }
