import { useEffect, useState } from "react";
import { ChevronDown, KeyRound, Pencil, Trash2, UserPlus, Users as UsersIcon } from "lucide-react";
import api from "../lib/api";
import { useFeedback } from "../context/FeedbackContext";
import { Spinner } from "../components/Loading";

const blank = { nim: "", name: "", password: "", role: "MAHASISWA" };
const field = "field w-full";

export default function Users() {
  const { showFeedback, requestConfirmation } = useFeedback();
  const [list, setList] = useState<any[]>([]);
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [meta, setMeta] = useState({ total: 0, totalPages: 1 });
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState(blank);
  const [editing, setEditing] = useState<any>(null);
  const [passwordUser, setPasswordUser] = useState<any>(null);
  const [password, setPassword] = useState("");
  const [importFile, setImportFile] = useState<File | null>(null);
  const [sort, setSort] = useState({ key: "createdAt", direction: "desc" });

  const load = () => api.get("/api/auth/users", { params: { search, page, limit: 25 } }).then((response) => {
    const data = response.data?.items ? response.data : { items: response.data, total: response.data.length, totalPages: 1 };
    setList(data.items);
    setMeta({ total: data.total, totalPages: data.totalPages });
  }).catch(() => showFeedback("Daftar user gagal dimuat.", "error"));
  useEffect(() => { const timer = window.setTimeout(load, 250); return () => window.clearTimeout(timer); }, [search, page]);
  const sorted = [...list].sort((a, b) => { const left = String(a[sort.key] || "").toLowerCase(); const right = String(b[sort.key] || "").toLowerCase(); return (left > right ? 1 : left < right ? -1 : 0) * (sort.direction === "asc" ? 1 : -1); });
  const changeSort = (key: string) => setSort((current) => current.key === key ? { key, direction: current.direction === "asc" ? "desc" : "asc" } : { key, direction: "asc" });
  const saveNew = async () => { if (!(await requestConfirmation(`User ${form.name || form.nim} akan ditambahkan ke sistem.`))) return; setSaving(true); try { await api.post("/api/auth/users", form); setForm(blank); await load(); showFeedback("User berhasil ditambahkan."); } catch (error: any) { showFeedback(error.response?.data?.message || "User gagal ditambahkan.", "error"); } finally { setSaving(false); } };
  const downloadTemplate = async () => { try { const response = await api.get("/api/auth/users/template", { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = "template-user-omni.xlsx"; link.click(); URL.revokeObjectURL(url); } catch (error: any) { showFeedback(error.response?.data?.message || "Template gagal diunduh.", "error"); } };
  const importUsers = async () => { if (!importFile) return; if (!(await requestConfirmation("Semua baris valid akan ditambahkan sebagai user baru. Jika ada satu baris invalid, seluruh import dibatalkan."))) return; const body = new FormData(); body.append("file", importFile); setSaving(true); try { const response = await api.post("/api/auth/users/import", body, { headers: { "Content-Type": "multipart/form-data" } }); setImportFile(null); await load(); showFeedback(response.data?.message || "User berhasil diimport."); } catch (error: any) { const details = error.response?.data?.errors; showFeedback(details?.length ? `${error.response?.data?.message} ${details.slice(0, 3).join(" ")}` : error.response?.data?.message || "Import user gagal.", "error"); } finally { setSaving(false); } };
  const saveEdit = async () => { setSaving(true); try { await api.put(`/api/auth/users/${editing.id}`, { nim: editing.nim, name: editing.name, role: editing.role }); setEditing(null); await load(); showFeedback("Data user berhasil diperbarui."); } catch (error: any) { showFeedback(error.response?.data?.message || "Data user gagal diperbarui.", "error"); } finally { setSaving(false); } };
  const changePassword = async () => { if (password.length < 8) return; setSaving(true); try { await api.patch(`/api/auth/users/${passwordUser.id}/password`, { password }); setPasswordUser(null); setPassword(""); showFeedback("Password user berhasil diubah."); } catch (error: any) { showFeedback(error.response?.data?.message || "Password gagal diubah.", "error"); } finally { setSaving(false); } };
  const remove = async (user: any) => { if (!(await requestConfirmation(`Akun ${user.name} akan dihapus permanen.`))) return; try { await api.delete(`/api/auth/users/${user.id}`); await load(); showFeedback("User berhasil dihapus."); } catch (error: any) { showFeedback(error.response?.data?.message || "User gagal dihapus.", "error"); } };

  return <div className="mx-auto max-w-6xl space-y-8">
    <header><p className="eyebrow">People & access</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Kelola user</h1><p className="mt-2 text-sm leading-6 text-zinc-500">Edit identitas, role, password, dan status akun pengguna.</p></header>
    <section className="section-card space-y-6">
      <div className="flex items-start gap-3"><UserPlus className="mt-1 shrink-0 text-violet-600" size={21} /><div><h2 className="font-semibold">Tambah user baru</h2><p className="mt-1 text-sm leading-6 text-zinc-500">Lengkapi identitas dasar dan tentukan role akses.</p></div></div>
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="block space-y-2 text-sm font-medium">NIM / identifier<input value={form.nim} onChange={(event) => setForm({ ...form, nim: event.target.value })} placeholder="Contoh: 20250001" className={field} /></label><label className="block space-y-2 text-sm font-medium">Nama lengkap<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Nama pengguna" className={field} /></label><label className="block space-y-2 text-sm font-medium">Password<input value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Minimal 8 karakter" type="password" className={field} /></label><RoleSelect value={form.role} setValue={(role) => setForm({ ...form, role })} /></div>
      <button disabled={saving} onClick={saveNew} className="primary-button"><UserPlus size={17} />{saving ? "Menyimpan..." : "Tambah user"}</button>
      <div className="border-t border-zinc-100 pt-6 dark:border-zinc-800"><div><h3 className="font-semibold">Import user dari Excel</h3><p className="mt-1 max-w-3xl text-sm leading-6 text-zinc-500">Gunakan template resmi dengan kolom <code>nim</code>, <code>name</code>, <code>password</code>, dan <code>role</code>. Maksimal 1.000 user per file.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-center"><button type="button" onClick={downloadTemplate} className="secondary-button justify-center">Download template</button><label className="block min-w-0"><span className="sr-only">Pilih file template user</span><input type="file" accept=".xlsx,.xls" onChange={(event) => setImportFile(event.target.files?.[0] || null)} className={`${field} file:mr-3 file:rounded-md file:border-0 file:bg-violet-100 file:px-3 file:py-1.5 file:text-xs file:font-semibold file:text-violet-700`} aria-label="Pilih file template user" /></label><button type="button" disabled={saving || !importFile} onClick={importUsers} className="primary-button justify-center">{saving ? <Spinner /> : <UserPlus size={17} />} Import user</button></div>{importFile && <p className="mt-2 text-xs text-zinc-500">File dipilih: <span className="font-medium text-zinc-700 dark:text-zinc-300">{importFile.name}</span></p>}<p className="mt-3 text-xs leading-5 text-zinc-400">Import bersifat transaksional: jika ada satu baris tidak valid atau identifier sudah terdaftar, tidak ada user yang ditambahkan.</p></div>
    </section>
    <section className="table-shell overflow-x-auto"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-zinc-100 px-5 py-5 dark:border-zinc-800"><div className="flex items-center gap-3"><UsersIcon size={18} className="text-violet-600" /><div><h2 className="text-sm font-semibold">Daftar pengguna</h2><p className="mt-1 text-xs text-zinc-500">{meta.total} akun · Online berarti aktif dalam 5 menit terakhir.</p></div></div><label className="w-full sm:w-72"><span className="sr-only">Cari user</span><input className={field} placeholder="Cari nama atau NIM..." value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></label></div><table className="w-full min-w-[950px] text-sm"><thead><tr><th><Sort label="NIM" field="nim" sort={sort} change={changeSort} /></th><th><Sort label="Nama" field="name" sort={sort} change={changeSort} /></th><th><Sort label="Role" field="role" sort={sort} change={changeSort} /></th><th>Status</th><th>Terakhir akses</th><th>Aksi</th></tr></thead><tbody>{sorted.map((user) => <tr key={user.id}><td>{user.nim}</td><td className="font-semibold">{user.name}</td><td><span className="rounded-full bg-violet-100 px-2 py-1 text-xs font-bold text-violet-700">{user.role}</span></td><td><span className={user.online ? "text-emerald-600" : "text-zinc-500"}>{user.online ? "● Online" : "● Offline"}</span></td><td className="whitespace-nowrap text-xs text-zinc-500">{user.lastSeenAt ? new Date(user.lastSeenAt).toLocaleString() : "Belum tercatat"}</td><td><div className="flex gap-2"><button className="secondary-button px-2 py-1.5 text-xs" onClick={() => setEditing({ ...user })}><Pencil size={14} /> Edit</button><button className="secondary-button px-2 py-1.5 text-xs" onClick={() => { setPasswordUser(user); setPassword(""); }}><KeyRound size={14} /> Password</button><button className="secondary-button px-2 py-1.5 text-xs text-red-600" onClick={() => remove(user)}><Trash2 size={14} /> Hapus</button></div></td></tr>)}</tbody></table>{sorted.length === 0 && <p className="p-8 text-center text-sm text-zinc-500">Tidak ada user yang cocok.</p>}{meta.totalPages > 1 && <div className="flex items-center justify-between border-t border-zinc-100 px-5 py-4 text-xs text-zinc-500 dark:border-zinc-800"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="secondary-button px-3 disabled:opacity-40">Sebelumnya</button><span>Halaman {page} dari {meta.totalPages}</span><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)} className="secondary-button px-3 disabled:opacity-40">Berikutnya</button></div>}</section>
    {editing && <UserModal user={editing} setUser={setEditing} onCancel={() => setEditing(null)} onSave={saveEdit} saving={saving} />}{passwordUser && <PasswordModal user={passwordUser} password={password} setPassword={setPassword} onCancel={() => setPasswordUser(null)} onSave={async () => { if (await requestConfirmation(`Password ${passwordUser.name} akan diganti.`)) await changePassword(); }} saving={saving} />}
  </div>;
}
function Sort({ label, field, sort, change }: any) { return <button className="font-semibold" onClick={() => change(field)}>{label} {sort.key === field ? (sort.direction === "asc" ? "↑" : "↓") : "↕"}</button>; }
function RoleSelect({ value, setValue }: { value: string; setValue: (role: string) => void }) { return <label className="block space-y-2 text-sm font-medium">Role pengguna<span className="select-shell"><select aria-label="Role pengguna" value={value} onChange={(event) => setValue(event.target.value)} className="field select-field"><option>MAHASISWA</option><option>DOSEN</option><option>ADMIN</option></select><ChevronDown className="select-chevron" size={17} /></span></label>; }
function UserModal({ user, setUser, onCancel, onSave, saving }: any) { return <div className="fixed inset-0 z-50 grid place-items-center bg-zinc-950/60 p-4" role="dialog" aria-modal="true"><div className="section-card w-full max-w-xl space-y-5"><div><p className="eyebrow">Administrasi user</p><h2 className="mt-2 text-xl font-bold">Edit data user</h2></div><div className="grid gap-4 sm:grid-cols-2"><label className="block space-y-2 text-sm font-medium">NIM / identifier<input className={field} value={user.nim} onChange={(event) => setUser({ ...user, nim: event.target.value })} placeholder="NIM / identifier" /></label><label className="block space-y-2 text-sm font-medium">Nama lengkap<input className={field} value={user.name} onChange={(event) => setUser({ ...user, name: event.target.value })} placeholder="Nama lengkap" /></label><RoleSelect value={user.role} setValue={(role: string) => setUser({ ...user, role })} /></div><div className="flex justify-end gap-3"><button disabled={saving} onClick={onCancel} className="secondary-button">Batal</button><button disabled={saving} onClick={onSave} className="primary-button">{saving ? <Spinner /> : <Pencil size={16} />} Simpan perubahan</button></div></div></div>; }
function PasswordModal({ user, password, setPassword, onCancel, onSave, saving }: any) { return <div className="fixed inset-0 z-50 grid place-items-center bg-zinc-950/60 p-4" role="dialog" aria-modal="true"><div className="section-card w-full max-w-md space-y-5"><div><p className="eyebrow">Keamanan akun</p><h2 className="mt-2 text-xl font-bold">Ganti password user</h2><p className="mt-2 text-sm text-zinc-500">{user.name} ({user.nim}) · minimal 8 karakter, maksimal 128.</p></div><label className="block space-y-2 text-sm font-medium">Password baru<input autoFocus type="password" minLength={8} maxLength={128} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Minimal 8 karakter" className={field} /></label><div className="flex justify-end gap-3"><button disabled={saving} onClick={onCancel} className="secondary-button">Batal</button><button disabled={saving || password.length < 8} onClick={onSave} className="primary-button">{saving ? <Spinner /> : <KeyRound size={16} />} Simpan password</button></div></div></div>; }
